config/routes.rb
Rails.application.routes.draw do
  root "matches#index"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :matches do
    resources :bets
  end
  resources :bet_champions, only: [:new, :create]
  get "my_bets" => "matches#my_bets"
  get "champions" => "bet_champions#index"
  get "ranking" => "users#ranking"
  get "allbets" => "users#all_bets"

  # Defines the root path route ("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bet.rb
class Bet < ApplicationRecord
  belongs_to :user
  belongs_to :match
  has_many :bets
  has_many :bet_first_rounds
  has_many :bet_second_rounds
  has_many :bet_third_rounds
  has_many :bet_finals
  validates :score_team_a, :score_team_b, :winner_id, presence: true
  validates :user_id, uniqueness: { scope: :match_id, message: "You can only bet once per match" }
  validate :validates_bet


  def validates_bet
    if self.score_team_a > self.score_team_b && self.winner_id != self.match.team_a_id
      errors.add(:winner_id, "Winner must be Team A")
    elsif self.score_team_a < self.score_team_b && self.winner_id != self.match.team_b_id
      errors.add(:winner_id, "Winner must be Team B")
    end
  end

  def update_score(score_team_a, score_team_b, winner_id)
    if self.score_team_a == score_team_a && self.score_team_b == score_team_b && self.winner_id == winner_id
      self.update(score: 10)  # Pontuação arbitrária para exemplo
    elsif self.score_team_a == score_team_a && self.score_team_b == score_team_b && self.winner_id != winner_id
      self.update(score: 5)
    elsif self.score_team_a == score_team_a || self.score_team_b == score_team_b
      if self.winner_id == winner_id
        self.update(score: 7)
      else
        self.update(score: 2)
      end
    elsif self.winner_id == winner_id
      self.update(score: 5)
    else
      self.update(score: 0)
    end
  end
end

app/models/bet_champion.rb
class BetChampion < ApplicationRecord
  belongs_to :user
  belongs_to :team, class_name: 'Team'
  validates :user, presence: true
  validates :team, presence: true
  validates :user_id, uniqueness: true
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :team_a, class_name: 'Team'
  belongs_to :team_b, class_name: 'Team'
  belongs_to :round
  validates :team_a, presence: true, uniqueness: { scope: :round_id }
  validates :team_b, presence: true, uniqueness: { scope: :round_id }
  validates :round_id, presence: true
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :match
  belongs_to :winner, class_name: 'Team', foreign_key: 'winner_id'
  belongs_to :team_a, class_name: 'Team', foreign_key: 'team_a_id'
  belongs_to :team_b, class_name: 'Team', foreign_key: 'team_b_id'
  after_save :refresh_bets

  private

  def refresh_bets
    bets = Bet.where(match_id: self.match_id)
    bets.each do |bet|
      bet.update_score(self.score_team_a, self.score_team_b, self.winner_id)
    end
  end
end

app/models/round.rb
class Round < ApplicationRecord
  has_many :matches
  validates :stage, presence: true, uniqueness: true
end

app/models/team.rb
class Team < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :bet_champions
  has_many :users, through: :bet_champions
  has_many :matches_as_team_a, class_name: 'Match', foreign_key: 'team_a_id'
  has_many :matches_as_team_b, class_name: 'Match', foreign_key: 'team_b_id'
  has_many :results_as_winner, class_name: 'Result', foreign_key: 'winner_id'
  has_many :results_as_team_a, class_name: 'Result', foreign_key: 'team_a_id'
  has_many :results_as_team_b, class_name: 'Result', foreign_key: 'team_b_id'
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true
  validates :encrypted_password, presence: true
  has_many :bet_champions
  has_many :teams, through: :bet_champions
  has_many :bets
  has_many :bet_first_rounds
  has_many :bet_second_rounds
  has_many :bet_third_rounds
  has_many :bet_finals

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bet_champions_controller.rb
class BetChampionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  def index
    @bets = BetChampion.all
  end

  def new
    @bet = BetChampion.new
    @teams = Team.all.map { |team| [team.name, team.id] }
  end

  def create
    @bet = BetChampion.new(strong_params)
    @bet.user_id = current_user.id
    if @bet.save
      redirect_to root_path, notice: 'Bet was successfully created.'
    else
      if @bet.errors.full_messages.to_sentence == "User You can only bet once for the champion"
        redirect_to new_match_bet_path(params[:match_id]), alert: "You can only bet once for the champion"
      else
        redirect_to new_match_bet_path(params[:match_id]), alert: "#{@bet.errors.full_messages.to_sentence}"
      end
    end
  end

  private

  def strong_params
    params.require(:bet_champion).permit(:team_id)
  end
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  def new
    @bet = Bet.new
  end

  def create
    @bet = Bet.new(strong_params)
    @bet.user_id = current_user.id
    @bet.match_id = params[:match_id]

    if @bet.save
      redirect_to root_path, notice: 'Bet was successfully created.'
    else
      if @bet.errors.full_messages.to_sentence == "User You can only bet once per match"
        redirect_to new_match_bet_path(params[:match_id]), alert: "You can only bet once per match"
      else
        redirect_to new_match_bet_path(params[:match_id]), alert: "#{@bet.errors.full_messages.to_sentence}"
      end
    end

  end

  private

  def strong_params
    params.require(:bet).permit(:score_team_a, :score_team_b, :winner_id)
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @matches = Match.where(round_id: 1)
    @matches2 = Match.where(round_id: 2)
    @matches3 = Match.where(round_id: 3)
    @matches4 = Match.where(round_id: 4)
  end

  def my_bets
    @bets = Bet.where(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def ranking
    @users = User.all
    @users.each do |user|
      bets = Bet.where(user_id: user.id)
      bets.each do |bet|
        user.score = user.score + bet.score
      end
    end
    @admins = @users.select { |user| user.admin == true }
    @users = @users - @admins
    @users = @users.sort_by { |user| user.score }.reverse
  end

  def all_bets
    @matches_1 = Match.where(round_id: 1)
    @matches_2 = Match.where(round_id: 2)
    @matches_3 = Match.where(round_id: 3)
    @matches_4 = Match.where(round_id: 4)
    @matches = @matches_4 + @matches_3 + @matches_2 + @matches_1
    @users = User.all
    @admins = @users.select { |user| user.admin == true }
    @users = @users - @admins
    @users = @users.sort_by { |user| user.score }.reverse
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bet_champions_helper.rb
module BetChampionsHelper
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bet_champions/index.html.erb
<div class="flex items-center justify-center" >
  <div class="flex w-2/3 min-h-full flex-col justify-center mx-6 my-8 lg:mx-8 shadow-md sm:rounded-lg">
    <table class="divide-y  divide-gray-200 text-sm rtl:text-right text-gray-500 dark:text-gray-400">
      <tbody >
        <% @bets.each do |bet| %>
          <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
            <th>
              <p class="px-6 py-3 text-center font-small break-all text-gray-400 max-w-1/3">
                <%= Team.find(bet.team_id).name %>
              </p>
              <p class="px-6  flex justify-center py-3 text-center font-small break-all text-gray-400 max-w-1/3">
                <%= render 'shared/flags_team_a', team: Team.find(bet.team_id) %>
              </p>
            </th>
            <th scope="row" class="px-6 py-4 max-w-80">
              <h3 class="px-6 py-3 text-center font-extrabold text-gray-800 break-all dark:text-white">
                <%=User.find(bet.user_id).username %>
              </h3>
            </th>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<div class="absolute right-20 bottom-20 ">
  <div >
    <%= link_to new_bet_champion_path do %>
      <?xml version="1.0"?><svg class="hover:fill-green-500" style="enable-background:new 0 0 24 24;" weight="80" height="80" version="1.1" viewBox="0 0 24 24" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" fill="#1F2937" xmlns:xlink="http://www.w3.org/1999/xlink"><g id="info"/><g id="icons"><path d="M12,1C5.9,1,1,5.9,1,12s4.9,11,11,11s11-4.9,11-11S18.1,1,12,1z M17,14h-3v3c0,1.1-0.9,2-2,2s-2-0.9-2-2v-3H7   c-1.1,0-2-0.9-2-2c0-1.1,0.9-2,2-2h3V7c0-1.1,0.9-2,2-2s2,0.9,2,2v3h3c1.1,0,2,0.9,2,2C19,13.1,18.1,14,17,14z" id="add"/></g></svg>
    <% end %>
  </div>
</div>

app/views/bet_champions/new.html.erb
<div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">
  <%= form_for @bet, url: bet_champions_path, html: { class: "nifty_form max-w-2/4 sm:mx-auto sm:w-full sm:max-w-sm" } do |f| %>
    <%= render 'shared/logo' %>
    <h2 class="mt-10 text-center text-2xl font-bold leading-9 tracking-tight text-gray-900">Create your Champion bet here</h2>

    <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
      <div class="mt-6">
        <div class="flex items-center justify-center my-2">
          <p class="block text-md font-extrabold leading-6 text-gray-900">Champion team:</p>
        </div>
        <div>
          <%= f.select :team_id, options_for_select(@teams), { prompt: "Select a team" }, { class: "block w-full rounded-md border-0 py-1.5 my-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" } %>
        </div>
      </div>

      <div class="mt-6">
        <%= f.submit "Create the bet", class: "flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
      </div>
    </div>
  <% end %>
</div>

app/views/bets/new.html.erb
<div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">
  <%= form_for @bet, url: { action: "create" }, html: { class: "nifty_form" } do |f| %>
    <div class="max-w-2/4 sm:mx-auto sm:w-full sm:max-w-sm">
      <%= render 'shared/logo' %>
      <h2 class="mt-10 text-center text-2xl font-bold leading-9 tracking-tight text-gray-900">Create your bet here</h2>
    </div>
    <% match = Match.find(params[:match_id].to_i) %>
    <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">

      <%# Team A Bet %>
      <div class="mt-6">
        <div class="flex items-center justify-between">
          <%= label_tag "team_a_bet", match.team_a.name, class: "block text-md font-extrabold leading-6 text-gray-900" %>
        </div>
        <div class="mt-2">
          <div class="mt-2">
          <%= f.number_field :score_team_a, in: 0..10, step: 1, class: "block w-full rounded-md border-0 py-1.5 my-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6", placeholder: "Score for Team A" %>
        </div>
      </div>

      <%# Team B Bet %>
      <div class="mt-6">
        <div class="flex items-center justify-between">
          <%= label_tag "team_b_bet", Match.find(params[:match_id].to_i).team_b.name, class: "block text-md font-extrabold leading-6 text-gray-900" %>
        </div>
        <div class="mt-2">
          <%= f.number_field :score_team_b, in: 0..10, step: 1, class: "block w-full rounded-md border-0 py-1.5 my-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6", placeholder: "Score for Team B" %>
        </div>
      </div>
      <div class="mt-6">
        <div class="flex items-center justify-center my-2">
          <p class="block text-md font-extrabold leading-6 text-gray-900">Winner team:</p>
          <%= select_tag 'bet[winner_id]', options_for_select([[match.team_a.name,match.team_a.id], [match.team_b.name,match.team_b.id]]), class: "block w-full rounded-md border-0 py-1.5 my-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
      </div>
      <%# Submit Button %>
      <div class="mt-6">
        <%= f.submit "Create the bet", class: "flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BolaoEuro</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/matches/my_bets.html.erb
<div class="flex items-center justify-center" >
  <div class="flex w-2/3 min-h-full flex-col justify-center mx-6 my-8 lg:mx-8 shadow-md sm:rounded-lg">
    <table class="divide-y  divide-gray-200 text-sm rtl:text-right ">
      <tbody >
        <% @bets.each do |bet| %>
          <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
            <% match =  Match.find(bet.match_id) %>
            <th>
              <p class="px-6 py-3 text-center font-small break-all text-gray-400 max-w-1/3">
                <%= match.team_a.name %>
              </p>
              <p class="px-6  flex justify-center py-3 text-center font-small break-all text-gray-400 max-w-1/3">
                <%= render 'shared/flags_team_a', team: match.team_a %>
              </p>
            </th>
            <th>
              <p class="px-6 py-3 text-center font-small break-all text-gray-400 max-w-1/3">
                <%= "#{bet.score_team_a} X #{bet.score_team_b}" %>
              </p>
            </th>
            <th>
              <p class="px-6 py-3 text-center font-small break-all text-gray-400 max-w-1/3">
                <%= match.team_b.name %>
              </p>
              <p class="px-6  flex justify-center py-3 text-center font-small break-all text-gray-400 max-w-1/3">
                <%= render 'shared/flags_team_a', team: match.team_b %>
              </p>
            </th>
            <th>
              <% if bet.score == 0 %>
                <p class="px-6 py-3 text-center font-small break-all text-red-600 max-w-1/3">
                  <%= bet.score %>
                </p>
              <% elsif bet.score == 2 %>
                <p class="px-6 py-3 text-center font-small break-all text-orange-600 max-w-1/3">
                  <%= bet.score %>
                </p>
              <% elsif bet.score == 5 %>
                <p class="px-6 py-3 text-center font-small break-all text-amber-500 max-w-1/3">
                  <%= bet.score %>
                </p>
              <% elsif bet.score == 7 %>
                <p class="px-6 py-3 text-center font-small break-all text-lime-500 max-w-1/3">
                  <%= bet.score %>
                </p>
              <% elsif bet.score == 10 %>
                <p class="px-6 py-3 text-center font-small break-all text-emerald-500 max-w-1/3">
                  <%= bet.score %>
                </p>
              <% end %>

            </th>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/shared/_flags_team_a.html.erb
<%= image_tag("https://res.cloudinary.com/dtz9smyye/image/upload/v1719694811/Bolao-euro/#{team.id}", alt: '', size: '80x80', class: "rounded py-1") %>

app/views/shared/_flags_team_b.html.erb
<%= image_tag("https://res.cloudinary.com/dtz9smyye/image/upload/v1719694811/Bolao-euro/#{match.team_b.id}", alt: '', size: '80x80', class: "rounded py-1") %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div  class="bg-blue-100 border-t-4 border-blue-500 rounded-b text-blue-900 px-5 py-3 shadow-md mb-4 fixed bottom-4 right-4 z-50" role="alert"
        data-controller="alert">
    <div class="flex items-center">
      <div class="py-1">
        <%= notice %>
      </div>
      <button type="button"
              class="ml-auto bg-transparent text-blue-500 hover:text-blue-700 focus:outline-none px-2"
              data-dismiss="alert"
              aria-label="Close"
              data-alert-target="button_notice"
              data-action="click->alert#close">
        X
      </button>
    </div>
  </div>
<% end %>

<% if alert %>
  <div  class="bg-yellow-100 border-t-4 border-yellow-500 rounded-b text-yellow-900 px-5 py-3 shadow-md mb-4 fixed bottom-4 right-4 z-50" role="alert"
        data-controller="alert">
    <div class="flex items-center">
      <div class="py-1">
        <%= alert %>
      </div>
      <button type="button"
              class="ml-auto bg-transparent text-yellow-500 hover:text-yellow-700 focus:outline-none px-2"
              data-dismiss="alert"
              aria-label="Close"
              data-alert-target="button_alert"
              data-action="click->alert#close">
        X
      </button>
    </div>
  </div>
<% end %>

app/views/shared/_logo.html.erb
<img class="mx-auto h-10 w-auto" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600" alt="Your Company">

app/views/shared/_navbar.html.erb
<nav class="bg-gray-800">
  <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="relative flex h-16 items-center justify-between">
      <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
        <div class="flex flex-shrink-0 items-center">
          <%= render 'shared/logo' %>
        </div>
        <div class="hidden sm:ml-6 sm:block">
          <div class="flex space-x-4">
            <% class_root = (@current_controller == 'Matches' && @current_action == 'index') ? "rounded-md bg-gray-900 px-3 py-2 text-sm font-medium text-white" : "rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white" %>
            <%= link_to 'Home', root_path, class: class_root  %>
            <%= link_to 'Champion Bets', champions_path, class: class_root  %>
            <%= link_to 'Ranking', ranking_path, class: class_root  %>
            <%= link_to 'All Bets', allbets_path, class: class_root  %>
            <% if current_user != nil %>
              <% class_my_bets = (@current_controller == 'Matches' && @current_action == 'my_bets') ? "rounded-md bg-gray-900 px-3 py-2 text-sm font-medium text-white" : "rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white" %>
              <%= link_to 'My Bets', my_bets_path, class: class_my_bets %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="relative ml-3">
        <% if current_user == nil %>
          <%= link_to new_user_session_path do %>
            <?xml version="1.0" ?><svg class="icon icon-tabler icon-tabler-login" fill="none" height="40" stroke="#ffffff" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" width="40" xmlns="http://www.w3.org/2000/svg"><path d="M0 0h24v24H0z" fill="none" stroke="none"/><path d="M14 8v-2a2 2 0 0 0 -2 -2h-7a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h7a2 2 0 0 0 2 -2v-2"/><path d="M20 12h-13l3 -3m0 6l-3 -3"/></svg>
          <% end %>
        <% else %>
          <div class="flex row items-center">
            <%= link_to destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" do %>
              <?xml version="1.0" ?><svg fill="none" height="40" viewBox="0 0 24 24" width="40" xmlns="http://www.w3.org/2000/svg"><path d="M17 16L21 12M21 12L17 8M21 12L7 12M13 16V17C13 18.6569 11.6569 20 10 20H6C4.34315 20 3 18.6569 3 17V7C3 5.34315 4.34315 4 6 4H10C11.6569 4 13 5.34315 13 7V8" stroke="#ffffff" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"/></svg>
            <% end %>
            <p class="ml-5 p-2 text-white"><%= current_user.username %></p>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <!-- Mobile menu. -->
  <div class="sm:hidden" id="mobile-menu">
    <div class="space-y-1 px-2 pb-3 pt-2">
      <% class_root = (@current_controller == 'Matches' && @current_action == 'index') ? "rounded-md bg-gray-900 px-3 py-2 text-sm font-medium text-white" : "rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white" %>
      <%= link_to 'Home', root_path, class: class_root  %>
      <%= link_to 'Champion Bets', champions_path, class: class_root  %>
      <%= link_to 'Ranking', ranking_path, class: class_root  %>
      <%= link_to 'All Bets', allbets_path, class: class_root  %>
      <% if current_user != nil %>
        <% class_my_bets = (@current_controller == 'Matches' && @current_action == 'my_bets') ? "rounded-md bg-gray-900 px-3 py-2 text-sm font-medium text-white" : "rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white" %>
        <%= link_to 'My Bets', my_bets_path, class: class_my_bets %>
      <% end %>
    </div>
  </div>
</nav>

app/views/users/all_bets.html.erb
<div class="flex items-center justify-center" >
  <div class="flex w-full min-h-full flex-col justify-center mx-6 my-8 lg:mx-8 shadow-md sm:rounded-lg">
    <table class="divide-y  divide-gray-200 text-sm rtl:text-right text-gray-500 dark:text-gray-400">
      <thead class="bg-gray-50 dark:bg-gray-700">
        <tr>
          <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">Match</th>
          <% @users.each do |user| %>
            <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">
              <%= user.username %>
            </th>
          <% end %>
        </tr>
      </thead>
      <tbody >
        <% @matches.each do |match| %>
          <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
            <th class="flex row  justify-center px-6 py-1">
              <div>
                <p class="px-6 py-1 text-center font-small break-all text-gray-400 max-w-1/3">
                  <%= match.team_a.name %>
                </p>
                <p class="px-6  flex justify-center py-1 text-center font-small break-all text-gray-400 max-w-1/3">
                  <%= render 'shared/flags_team_a', team: match.team_a %>
                </p>
              </div>
              <p class="px-6 py-1 text-center font-small break-all text-gray-400 max-w-1/4">
                X
              </p>
              <div>
                <p class="px-6 py-1 text-center font-small break-all text-gray-400 max-w-1/3">
                  <%= match.team_b.name %>
                </p>
                <p class="px-6  flex justify-center py-1 text-center font-small break-all text-gray-400 max-w-1/3">
                  <%= render 'shared/flags_team_a', team: match.team_b %>
                </p>
              </div>
            </th>
            <% @users.each do |user| %>
             <th>
                <% bet = Bet.find_by(match_id: match.id, user_id: user.id) %>
                <% if bet.present? %>
                  <p>
                    <%= bet.score_team_a %> X <%= bet.score_team_b %>
                  </p>
                  <p>
                    <%= Team.find(bet.winner_id).name %>
                  </p>
                <% else %>
                  <p>Sem aposta</p>
                <% end %>
              </th>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/ranking.html.erb
<div class="relative">
  <div class="flex items-center justify-center">
    <div class="flex w-2/3 min-h-full flex-col justify-center mx-6 my-8 lg:mx-8 shadow-md sm:rounded-lg">
      <table class="divide-y divide-gray-200 text-sm rtl:text-right text-gray-500 dark:text-gray-400">
        <tbody>
          <% @users.each do |user| %>
            <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
              <td class="px-6 py-3 text-center font-small break-all text-gray-400 max-w-1/3">
                <%= user.username %>
              </td>
              <td class="px-6 py-4 max-w-80">
                <h3 class="px-6 py-3 text-center font-extrabold text-gray-800 break-all dark:text-white">
                  <%= user.score %>
                </h3>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>